### ISSUE TITLE
DEADLINE_EXCEEDED: Deadline exceeded

### ISSUE THREAD

**Issue by bitcoinvsalts** [googleapis/nodejs-automl#568] opened 2021-12-03 17:06 UTC
I am using `"@google-cloud/automl": "^2.5.1",`

Here is my code:

`
client.predict({
name: modelFullId,
payload: inputs,
params: {feature_importance: false},
timeout: 20000
})
.then( async responses => {
})
.catch(err => {
})
`

Here is the error:

`DEADLINE_EXCEEDED: Deadline exceeded
Dec 3 10:21:01 class5-bva3 app[web] info     at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
Dec 3 10:21:01 class5-bva3 app[web] info     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:180:52)
Dec 3 10:21:01 class5-bva3 app[web] info     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
Dec 3 10:21:01 class5-bva3 app[web] info     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
Dec 3 10:21:01 class5-bva3 app[web] info     at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:160:78
Dec 3 10:21:01 class5-bva3 app[web] info     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
Dec 3 10:21:01 class5-bva3 app[web] info   code: 4,
Dec 3 10:21:01 class5-bva3 app[web] info   details: 'Deadline exceeded',
Dec 3 10:21:01 class5-bva3 app[web] info   metadata: Metadata { internalRepr: Map(0) {}, options: {} }`

I tried many ways but this error still shows up.

**Comment by bitcoinvsalts** [comment] 2021-12-06 13:11
I need help on this. I tried everything and I still get this issue. Does the issue come from the GCS side?

**Comment by bitcoinvsalts** [comment] 2021-12-09 19:24
Please I need help on this. 

Does the issue come from the GCS side?

**Comment by kweinmeister** [comment] 2021-12-13 01:39
Hello, I ran our tabular prediction [sample code](https://github.com/googleapis/nodejs-automl/blob/main/samples/tables/predict.v1beta1.js) using the inputs in the [test](https://github.com/googleapis/nodejs-automl/blob/main/samples/test/automlTablesPredict.v1beta1.test.js). It was successful - returning a result without any deadline exceeded error. I might suggest starting with one of the [samples](https://github.com/googleapis/nodejs-automl/tree/main/samples) that's most similar to what you're trying to do.

**Comment by bitcoinvsalts** [comment] 2021-12-13 11:20
This issue only comes once in a while. I would say around 4-5% of my
prediction requests.

**Comment by kweinmeister** [comment] 2021-12-14 20:28
OK, thanks for the extra info. I just reran a looped test on my end and it passed 100 times in a row. So, I am still having trouble reproducing this error. If you haven't already, I might suggest adding retry logic to your client code.

**Comment by bitcoinvsalts** [comment] 2021-12-14 20:30
Thanks @kweinmeister Could you try with 1000 times?

**Comment by ivanmkc** [comment] 2022-05-23 17:59
We can probably close due to non-response

**Comment by kweinmeister** [comment] 2022-07-06 23:19
Per @ivanmkc, we are closing this issue. If you still are seeing the same behavior, please feel free to reopen.

**Closed** 2022-07-06 23:18 UTC
Labels: type: question, api: automl
