### ISSUE TITLE
[AutoML Tables] payload.payload; Message: Required field not set(js)

### ISSUE THREAD

**Issue by XinyueZ** [googleapis/nodejs-automl#412] opened 2020-06-13 15:44 UTC
I get this error when I query my AutoML Tables model when I deploy a Firebase cloud function.

`payload.payload; Message: Required field not set.` 

additional stacktrace:
```
    at Object.exports.createStatusError (/srv/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/srv/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/srv/node_modules/grpc/src/client_interceptors.js:847:24)
  code: 3,
  metadata: 
   Metadata {
     _internal_repr: 
      { 'google.rpc.badrequest-bin': [Array],
        'grpc-status-details-bin': [Array],
        'grpc-server-stats-bin': [Array] },
     flags: 0 },
  details: 'List of found errors:\t1.Field: name; Message: The provided location ID doesn\'t match the endpoint. For automl.googleapis.com, the valid location ID is `us-central1`. For eu-automl.googleapis.com, the valid location ID is `eu`.\t',
  note: 'Exception occurred in retry method that was not classified as transient' } 
```

The payload should have been set as demo showing.

>And I believe I have set the location in `eu` correctly. 
My model was deployed in `eu`, so I have to use `eu-automl.googleapis.com`.

However, I believe I have coded correctly:

```javascript
const project = 'some model project';
const region = 'eu';
const model = 'TBL82342424234';

const automl = require('@google-cloud/automl').v1beta1;
const clientOptions = { apiEndpoint: 'eu-automl.googleapis.com' };
const predictionClient = new automl.PredictionServiceClient(clientOptions);


const projectLocation = modelClient.locationPath(project, region);

const payload = {
        row: {
            values: [{ stringValue: "hello, world" }],
        },
 };
const requestPrediction = {
        name: predictionClient.modelPath(project, region, model),
        payload: payload,
        params: { feature_importance: true },
 };
predictionClient.predict(requestPrediction) .......
```

**Comment by munkhuushmgl** [comment] 2020-06-22 21:05
I am looking into it!

**Comment by munkhuushmgl** [comment] 2020-06-24 18:17
@XinyueZ which AutoML product you are using prediction for? Translation or NL?

Also your payload may not be right

try the following code:
```
     payload: {
        textSnippet: {
          content: content,
          mimeType: 'text/plain', // Types: 'test/plain', 'text/html'
        },
      }
```
Let me know if this helps or not

**Comment by munkhuushmgl** [comment] 2020-06-24 21:44
@XinyueZ Have you tried with this?
adding :443 to endpouint
```
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/8d1b1aa6683397be8dda1bafd293704a34376ac8/tables/automl/automl_tables_set_endpoint.py#L24
```

**Comment by XinyueZ** [comment] 2020-06-24 21:49
> @XinyueZ Have you tried with this?
> adding :443 to endpouint
> 
> https://github.com/GoogleCloudPlatform/python-docs-samples/blob/8d1b1aa6683397be8dda1bafd293704a34376ac8/tables/automl/automl_tables_set_endpoint.py#L24

I believed I have tried with port, it did not work.
I have currently workaround with Python as well and it works, however, my prefer is Node.js .

**Comment by XinyueZ** [comment] 2020-06-24 21:51
Please try once on your side, if you don't have problem, I will retry here again.
For this issue, I had already digged in 2 days without an outcome 🙊 😅

**Comment by munkhuushmgl** [comment] 2020-06-24 22:47
@XinyueZ okay, I will try to reproduce this error on my end, and it will probably take some time because MODEL training in EU region.

**Comment by munkhuushmgl** [comment] 2020-07-07 20:31
@XinyueZ I was able to do it with [predict-gcs-source-gcs-dest.v1beta1.js](https://github.com/googleapis/nodejs-automl/blob/master/samples/tables/predict-gcs-source-gcs-dest.v1beta1.js)
![image](https://user-images.githubusercontent.com/45373284/86839182-f695ff80-c055-11ea-929b-a891eddd5ea9.png)

model is EU region
buckets are in EU region

**Comment by munkhuushmgl** [comment] 2020-07-07 20:33
```
async function main(
  projectId = 'your-gcp-project',
  computeRegion = 'eu',
  modelId = 'TBL123412312412312312',
  inputUri = 'gs://input-bucket-in-europe/bank-marketing.csv',
  outputUriPrefix = 'gs://output-bucket-in-europe/'
) {
  // [START automl_tables_predict_using_gcs_source_and_gcs_dest]
  const automl = require('@google-cloud/automl');

  const clientOptions = {apiEndpoint: 'eu-automl.googleapis.com'};
  // Create client for prediction service.
  const client = new automl.v1beta1.PredictionServiceClient(clientOptions);


  // Get the full path of the model.
  const modelFullId = client.modelPath(projectId, computeRegion, modelId);

  // Get the multiple Google Cloud Storage input URIs.
  const inputUris = inputUri.split(',');
  const inputConfig = {
    gcsSource: {
      inputUris: inputUris,
    },
  };

  // Get the Google Cloud Storage output URI.
  const outputConfig = {
    gcsDestination: {
      outputUriPrefix: outputUriPrefix,
    },
  };

  // Get the latest state of long-running operation.
  client
    .batchPredict({
      name: modelFullId,
      inputConfig: inputConfig,
      outputConfig: outputConfig,
    })
    .then(responses => {
      const operation = responses[1];
      console.log(`Operation name: ${operation.name}`);
    })
    .catch(err => {
      console.error(err);
    });
  // [END automl_tables_predict_using_gcs_source_and_gcs_dest]
}

```

**Comment by munkhuushmgl** [comment] 2020-07-07 20:35
What is the reason behind using modelClient in your code snippet?
@XinyueZ

**Comment by XinyueZ** [comment] 2020-07-07 20:36
@munkhuushmgl Strange, my next question, where do you deploy this script? My working case is that I deploy this on the Firebase Cloud Functions.

**Comment by XinyueZ** [comment] 2020-07-07 20:37
So, my use-case is to deploy a cloud function as endpoint for prediction, however, I tried several days with negative outcomes.

**Comment by munkhuushmgl** [comment] 2020-07-07 20:40
@XinyueZ I have not deployed as firebase cloud functions. I would ask that from firebase cloud function team.

**Comment by munkhuushmgl** [comment] 2020-07-07 20:44
Also I have customized your code snippet and ran locally. Looks like it is working fine (output is incorrect due to invalid input)

Here it is code snippet I customized:

```
const project = 'java-*****************';
const region = 'eu';
const model = 'TBL55000000000000000';

const automl = require('@google-cloud/automl').v1beta1;
const clientOptions = {apiEndpoint: 'eu-automl.googleapis.com'};
const predictionClient = new automl.PredictionServiceClient(clientOptions);

const payload = {
  row: {
    values: [{stringValue: 'hello, world'}],
  },
};
const modelFullId = predictionClient.modelPath(project, region, model);

predictionClient
  .predict({
    name: modelFullId,
    payload: payload,
    params: {feature_importance: true},
  })
  .then(responses => {
    console.log(responses);
    console.log('Prediction results:');

    for (const result of responses[0].payload) {
      console.log(`Predicted class name: ${result.displayName}`);
      console.log(`Predicted class score: ${result.tables.score}`);

      // Get features of top importance
      const featureList = result.tables.tablesModelColumnInfo.map(
        columnInfo => {
          return {
            importance: columnInfo.featureImportance,
            displayName: columnInfo.columnDisplayName,
          };
        }
      );
      // Sort features by their importance, highest importance first
      featureList.sort((a, b) => {
        return b.importance - a.importance;
      });

      // Print top 10 important features
      console.log('Features of top importance');
      console.log(featureList.slice(0, 10));
    }
  })
  .catch(err => {
    console.error(err);
  });

```

**Comment by XinyueZ** [comment] 2020-07-07 20:46
Got it, I will try

**Comment by munkhuushmgl** [comment] 2020-07-07 23:05
Closing this issue, feel free to reopen if u still having trouble with this.

**Closed by munkhuushmgl** 2020-07-07 23:05 UTC
Labels: api: automl, needs more info, priority: p2
